name: Dockerize Nestjs Application

runs:
  using: "composite"
  steps:
    - name: Download build output
      uses: actions/download-artifact@v3
      shell: bash
      with:
        name: build-output

    - name: Log in to GitHub Docker registry
      uses: docker/login-action@v2
      shell: bash
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image name
      shell: bash
      run: |
        


    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/stamper-labs/tnk-boards-api:latest