name: Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - 'main'

jobs:
  build:
    name: Build Workflows Toolkit
    uses: ./src/wflows/v1/gradle-basic-build.yml