name: Release A New Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release Core Workflows
    uses: ./.github/workflows/gradle-basic-release.yml
