name: Release Core Workflows Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-gradle-app:
    name: Release Gradle App
    uses: ./.github/workflows/gradle-basic-release.yml

