name: Build Gradle Basic Application

on:
  workflow_call:

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get PR Title
        id: get_pr_title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          echo "pr-title=$PR_TITLE" >> $GITHUB_OUTPUT

      - name: Validate PR Title
        uses: ./.github/actions/conventional-pr-title/v1
        with:
          pr-title: ${{ steps.get_pr_title.outputs.pr-title }}