name: Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - 'main'

jobs:
  build:
    name: Build Workflows Toolkit
    uses: ./.github/workflows/blueprint/v1/gradle-basic-local-build.yml
