name: Build Nestjs Application

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: The NodeJS version to build the app with.
        default: "20"
      release-mode:
        required: false
        type: boolean
        description: Determines if the action must bump a new version after the build.
        default: false

jobs:
  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Formatting
        run: npm run format:check

      - name: Code linting
        run: npm run lint

      - name: Run Unit Test With Coverage
        run: npm run test:cov

      - name: Build Application
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            dist/
            package.json
            package-lock.json
            Dockerfile

      - name: Set Up Git User
        if: ${{ inputs.release-mode }}
        run: |
          git config user.email "mcwiise@gmail.com"
          git config user.name "Captain Mcwiise"

      - name: Bump A New Version
        if: ${{ inputs.release-mode }}
        run: npm run release
