name: On push to main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config user.email "mcwiise@gmail.com"
          git config user.name "Captain Mcwiise"
          git branch

      - name: Create and Push Release Tag
        run: ./gradlew release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
