name: On push to main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release-core-flows:
    name: Release Core Flows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Install yarn@1.22.22
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          
      - name: Clean and install
        run: yarn install --frozen-lockfile

      - name: Setup git user
        run: |
          git config user.email "mcwiise@gmail.com"
          git config user.name "Captain Mcwiise"

      - name: Bump a new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

      - name: print released version
        run: node -p "require('./package.json').version"
        
