name: On push to main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config user.email "mcwiise@gmail.com"
          git config user.name "Captain Mcwiise"

      - name: Create and Push Release Tag
        id: create_release
        run: |
          ./gradlew release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: |
          RELEASED_TAG="v${{ steps.create_release.outputs.released-version }}"
          if git rev-parse "$RELEASED_TAG" >/dev/null 2>&1; then
            echo "Proceeding to create GitHub release for $RELEASED_TAG"
            gh release create "$RELEASED_TAG" \
            --title "$RELEASED_TAG" \
            --notes "This is an automated release for version $RELEASED_TAG."
          else
            echo "Tag $RELEASED_TAG does not exist. GitHub Release cannot be created."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}