name: On pull request to main

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - 'main'

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get PR Title
        id: get_pr_title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          echo "pr_title=$PR_TITLE" >> $GITHUB_ENV  # Use $GITHUB_ENV for setting outputs

      - name: Validate PR Title
        uses: .src/core/conventional-pr-title/v1
        with:
          pr-title: ${{ env.pr_title }}  # Use $env to access the variable set by $GITHUB_ENV