name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release Workflows Toolkit
    uses: ./.github/workflows/blueprint/v1/gradle-basic-release.yml
